package io.github.aedev.flow.data.sponsordetection

import android.content.Context
import io.github.aedev.flow.data.model.SponsorBlockSegment
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.File
import java.security.MessageDigest
import kotlin.math.max
import kotlin.math.min
import kotlin.random.Random

internal fun sponsorTranscriptSha256(transcript: SponsorTranscriptPayload): String {
    val canonical =
        buildString {
            append(transcript.languageTag)
            append('|')
            append(transcript.source.name)
            append('|')
            append(transcript.isAutoGenerated)
            transcript.cues.forEach { cue ->
                append('\n')
                append(cue.startMs)
                append('|')
                append(cue.endMs)
                append('|')
                append(cue.text)
            }
        }
    return sha256(canonical)
}

internal fun sha256(value: String): String =
    MessageDigest
        .getInstance("SHA-256")
        .digest(value.toByteArray(Charsets.UTF_8))
        .joinToString("") { "%02x".format(it) }

internal fun sha256File(file: File): String {
    val digest = MessageDigest.getInstance("SHA-256")
    file.inputStream().buffered().use { input ->
        val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
        var read = input.read(buffer)
        while (read >= 0) {
            digest.update(buffer, 0, read)
            read = input.read(buffer)
        }
    }
    return digest.digest().joinToString("") { "%02x".format(it) }
}

internal fun compareSponsorSpans(
    predictions: List<SponsorPredictedSpan>,
    apiSegments: List<SponsorBlockSegment>,
    minimumIou: Double = 0.5,
): Pair<List<SponsorApiSpan>, SponsorComparison> {
    val apiSpans =
        apiSegments
            .asSequence()
            .filter { it.category in SPONSOR_MODEL_CATEGORIES }
            .mapNotNull { segment ->
                val start = (segment.startTime * 1000).toLong()
                val end = (segment.endTime * 1000).toLong()
                if (start < 0 || end <= start) null else SponsorApiSpan(segment.uuid, start, end, segment.category)
            }.toList()
    val candidates =
        predictions
            .flatMap { prediction ->
                apiSpans.mapNotNull { api ->
                    val overlap = min(prediction.endMs, api.endMs) - max(prediction.startMs, api.startMs)
                    if (overlap <= 0 || prediction.category != api.category) return@mapNotNull null
                    val union = max(prediction.endMs, api.endMs) - min(prediction.startMs, api.startMs)
                    val iou = overlap.toDouble() / union
                    if (iou < minimumIou) null else Triple(prediction, api, iou)
                }
            }.sortedWith(
                compareByDescending<Triple<SponsorPredictedSpan, SponsorApiSpan, Double>> { it.third }
                    .thenBy { it.first.spanId }
                    .thenBy { it.second.id },
            )
    val usedPredictions = mutableSetOf<String>()
    val usedApi = mutableSetOf<String>()
    val matches =
        buildList {
            candidates.forEach { (prediction, api, iou) ->
                if (prediction.spanId !in usedPredictions && api.id !in usedApi) {
                    usedPredictions += prediction.spanId
                    usedApi += api.id
                    add(
                        SponsorSpanMatch(
                            predictionId = prediction.spanId,
                            apiId = api.id,
                            iou = iou,
                            startErrorMs = prediction.startMs - api.startMs,
                            endErrorMs = prediction.endMs - api.endMs,
                        ),
                    )
                }
            }
        }
    return apiSpans to
        SponsorComparison(
            matches = matches,
            modelOnlyIds = predictions.map { it.spanId }.filterNot(usedPredictions::contains),
            apiOnlyIds = apiSpans.map { it.id }.filterNot(usedApi::contains),
        )
}

internal fun selectSponsorPlaybackSegments(
    apiSegments: List<SponsorBlockSegment>,
    inference: SponsorInferenceResult,
): List<SponsorBlockSegment> = if (apiSegments.isNotEmpty()) apiSegments else inference.playbackSegments

/**
 * Seek-bar marks: playback/API segments plus on-device predictions that are
 * not already in that list. Review can show model-only spans even when the
 * API is authoritative for skip, so those still need a timeline overlay.
 */
fun overlaySponsorTimelineSegments(
    playbackSegments: List<SponsorBlockSegment>,
    detection: SponsorDetectionUiState,
): List<SponsorBlockSegment> {
    val videoId = detection.videoId ?: return playbackSegments
    if (detection.predictions.isEmpty()) return playbackSegments
    val existing = playbackSegments.mapTo(HashSet()) { it.uuid }
    val extra =
        detection.predictions
            .map { it.asSponsorBlockSegment(videoId) }
            .filter { it.uuid !in existing }
    return if (extra.isEmpty()) playbackSegments else playbackSegments + extra
}

internal fun focusedTranscriptWindows(
    transcript: SponsorTranscriptPayload,
    predictions: List<SponsorPredictedSpan>,
    apiSpans: List<SponsorApiSpan>,
    contextMs: Long = 30_000,
    negativeWindowMs: Long = 60_000,
    maxNegativeWindows: Int = 3,
    seed: String,
): List<SponsorTranscriptWindow> {
    if (transcript.cues.isEmpty()) return emptyList()
    val transcriptEnd = transcript.cues.maxOf { it.endMs }
    val protected =
        (predictions.map { it.startMs to it.endMs } + apiSpans.map { it.startMs to it.endMs })
            .map { (start, end) -> max(0, start - contextMs) to min(transcriptEnd, end + contextMs) }
            .sortedBy { it.first }
            .fold(mutableListOf<Pair<Long, Long>>()) { merged, range ->
                val previous = merged.lastOrNull()
                if (previous != null && range.first <= previous.second) {
                    merged[merged.lastIndex] = previous.first to max(previous.second, range.second)
                } else {
                    merged += range
                }
                merged
            }
    val contextWindows = protected.mapNotNull { range -> transcriptWindow(transcript, range, SponsorTranscriptWindowKind.SEGMENT_CONTEXT) }
    val possibleStarts =
        transcript.cues
            .asSequence()
            .map { it.startMs }
            .filter { start ->
                val end = min(transcriptEnd, start + negativeWindowMs)
                protected.none { range -> start < range.second && end > range.first }
            }.distinct()
            .toMutableList()
    possibleStarts.shuffle(Random(seed.hashCode()))
    val negatives =
        possibleStarts
            .take(maxNegativeWindows)
            .mapNotNull { start ->
                transcriptWindow(
                    transcript,
                    start to min(transcriptEnd, start + negativeWindowMs),
                    SponsorTranscriptWindowKind.WEAK_NEGATIVE,
                )
            }
    return contextWindows + negatives
}

private fun transcriptWindow(
    transcript: SponsorTranscriptPayload,
    range: Pair<Long, Long>,
    kind: SponsorTranscriptWindowKind,
): SponsorTranscriptWindow? {
    val cues =
        transcript.cues
            .filter { it.startMs < range.second && it.endMs > range.first }
            .map { SponsorTranscriptCue(it.startMs, it.endMs, it.text) }
    if (cues.isEmpty()) return null
    return SponsorTranscriptWindow(kind, range.first, range.second, cues)
}

internal interface SponsorPredictionCache {
    suspend fun get(
        videoId: String,
        transcript: SponsorTranscriptPayload,
    ): SponsorInferenceResult?

    suspend fun put(result: SponsorInferenceResult)
}

/**
 * Cache identity for one prediction. It binds the model, the tokenizer and the
 * on-device decode logic so that changing any of them (window size, thresholds,
 * minimum span, continuity merge, ...) invalidates previously cached spans.
 */
internal fun sponsorPredictionCacheKey(
    videoId: String,
    transcriptHash: String,
    logicVersion: Int = SPONSOR_DECODE_LOGIC_VERSION,
): String = sha256("$videoId|$SPONSOR_MODEL_SHA256|$SPONSOR_TOKENIZER_SHA256|$logicVersion|$transcriptHash")

internal class SponsorInferenceCache(
    private val directory: File,
    private val json: Json = Json { ignoreUnknownKeys = true },
    private val nowMs: () -> Long = { System.currentTimeMillis() },
    private val maxAgeMs: Long = DEFAULT_MAX_AGE_MS,
    private val maxEntries: Int = DEFAULT_MAX_ENTRIES,
) : SponsorPredictionCache {
    constructor(context: Context) : this(File(context.cacheDir, "sponsor_detection"))

    override suspend fun get(
        videoId: String,
        transcript: SponsorTranscriptPayload,
    ): SponsorInferenceResult? =
        withContext(Dispatchers.IO) {
            val transcriptHash = sponsorTranscriptSha256(transcript)
            val key = cacheKey(videoId, transcriptHash)
            val file = File(directory, "$key.json")
            val entry = runCatching { json.decodeFromString<CachedInference>(file.readText()) }.getOrNull() ?: return@withContext null
            if (nowMs() - entry.createdAtEpochMs > maxAgeMs) {
                file.delete()
                return@withContext null
            }
            file.setLastModified(nowMs())
            SponsorInferenceResult(
                videoId = videoId,
                transcript = transcript,
                transcriptSha256 = transcriptHash,
                spans = entry.spans,
                windowCount = entry.windowCount,
                confidenceThreshold = entry.confidenceThreshold,
                inferenceMs = entry.inferenceMs,
                fromCache = true,
            )
        }

    override suspend fun put(result: SponsorInferenceResult) =
        withContext(Dispatchers.IO) {
            directory.mkdirs()
            val entry =
                CachedInference(
                    createdAtEpochMs = nowMs(),
                    inferenceMs = result.inferenceMs,
                    spans = result.spans,
                    windowCount = result.windowCount,
                    confidenceThreshold = result.confidenceThreshold,
                )
            val file = File(directory, "${cacheKey(result.videoId, result.transcriptSha256)}.json")
            file.writeText(json.encodeToString(entry))
            file.setLastModified(nowMs())
            directory
                .listFiles { file -> file.extension == "json" }
                .orEmpty()
                .sortedByDescending(File::lastModified)
                .drop(maxEntries)
                .forEach(File::delete)
        }

    private fun cacheKey(
        videoId: String,
        transcriptHash: String,
    ): String = sponsorPredictionCacheKey(videoId, transcriptHash)

    @Serializable
    private data class CachedInference(
        val createdAtEpochMs: Long,
        val inferenceMs: Long,
        val spans: List<SponsorPredictedSpan>,
        val windowCount: Int = 0,
        val confidenceThreshold: Double = 0.0,
    )

    private companion object {
        const val DEFAULT_MAX_ENTRIES = 500
        const val DEFAULT_MAX_AGE_MS = 30L * 24L * 60L * 60L * 1000L
    }
}
